name: Nightly Tests

on:
  schedule:
    - cron: "0 0 * * *" # This runs at midnight UTC every day

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13.1
        uses: actions/setup-python@v3
        with:
          python-version: 3.13.1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Launch integration tests
        run: |
          ./tests/integration/run.sh
